### ISSUE TITLE
When no search results are found, Power+ says that the class has no assignments and the search box disappears

### ISSUE THREAD

**Issue by 3052** [jottocraft/dtps#11]
**Describe the bug**
When no search results are found, Power+ says that the class has no assignments and the search box disappears

**Repo steps**
- Go to any class with assignments
- Search something that won't show any results, i.e. "fjsdakfjsadjfsdajfoiasjfoi"
- Power+ says that the class has no assignments, even though it's just an issue with search not finding any results

**Expected behavior:**
- The results are empty or a card shows that says that there were no results found

**Actual behavior:**
- Power+ says that the class has no assignments

**Desktop (please complete the following information):**
 - OS with version: [e.g. Windows 10, macOS Mojave]

**Comment by jottocraft** [comment]
This issue has been addressed and a fix is included in build https://github.com/jottocraft/dtps/commit/e56b65ef26c5c7fe1ea4f428787cae16fcc17a39. The fix will hit stable with the February 2019 update (v1.5.0)
