### ISSUE TITLE
[BUG] MAJOR OH NO !!!!!!!

### ISSUE THREAD

**Issue by 3052** [jottocraft/dtps#12]
when you click the bug icon and do the report thing if you chose cancel it will still send a report so i sent some with no reason and it gives you an id to give you an IDea about how bad and breaking this is

**Comment by 3052** [comment]
PS>>>>> you need to hit ok on the first prompt but if u aceidnetaly click ok then the cancel button sends it anyway

**Comment by jottocraft** [comment]
the first prompt is the only one you can cancel it. I could add this for the other prompt, but bug reporting isn't really a feature targeted at end-users so it doesn't really matter as much.
