### ISSUE TITLE
[BUG] Links on the announecments are too hard to read and clip out of the box

### ISSUE THREAD

**Issue by 3052** [jottocraft/dtps#14]
**Capture Power+ logs**
- Do whatever you need to do to make the bug happen
- If this issue is related to a class, make sure that class is selected in the sidebar
- Click the 3 dots at the top-right corner of the screen, then click the about tab on the sidebar
- Click on the Advanced Options link near the bottom of the page
- Click on send a bug report and enter a brief description of the issue, and copy the report ID it gives you

Paste the ReportID here:
REPORT_iefiduduf8uf89eruf89

**Steps you take to make the bug happen:**
Open school HP chromebook. Load power+ and visit the dashboard. Scroll down to announcements and click on one with a link.

**Description of the bug:**
Link text goes out of the box. On blue themed classes (and some other themes) it becomes very hard if not impossible to read.

**Comment by 3052** [comment]
![Screenshot 2019-04-10 at 4 41 34 PM](https://user-images.githubusercontent.com/31232125/55967210-bc5d6880-5c2e-11e9-9c1f-0bfa3b2003f6.png)

**Comment by jottocraft** [comment]
I haven't been able to get to fixing this just yet since I've been working on bringing over more canvas features to Power+ for Canvas all day today. I'll push a fix by 6:00 PM PDT to both dev and stable versions of Power+.

**Comment by jottocraft** [comment]
This issue has been patched as of https://github.com/jottocraft/dtps/commit/2ad9f03738ab3c3ca0467cc8e6995697a24776ae (dev) and https://github.com/jottocraft/dtps/commit/a39b35af118141d134208de8cd7470dcdcef6481 (stable)

**Comment by 3052** [comment]
![Screenshot 2019-04-12 at 9 48 59 AM](https://user-images.githubusercontent.com/31232125/56053212-66f58a00-5d08-11e9-9244-a251989d978d.png)
Thank you for the fix, there is still a problem though. Your fix only somewhat fixes the issue. There is still an issue where long links are cut out, and now instead of going outside of the box, the link is just cut off. Please try to put the rest of the link in a new line, it's really weird and annoying to not be able to view the entire link because of the way you cut it off.
