### ISSUE TITLE
Discussions tab

### ISSUE THREAD

**Issue by russellb1223** [jottocraft/dtps#16]
Can your next tab be the discussions tab?

**Comment by jottocraft** [comment]
Right now, I'm working on implementing important Canvas features, primarily the new CBL gradebook and other class information features like Sylabus support, classmates list, and class home pages. Once those are ready, I'll start working on adding discussions to Power+. Implementing all of those other features and getting Canvas out of beta may take a while, so I can't provide any ETA for discussions right now.

**Comment by jottocraft** [comment]
As of https://github.com/jottocraft/dtps/commit/7a8357b53b0ea7f39eedbdd4245e37ebbf7b82ed, the discussions tab is live as a beta feature

Limitations:
* Discussions are currently read-only
* Threaded discussions only support 3 levels of replies
* This is a beta, so certain discussions may not work properly
