### ISSUE TITLE
Be able to view which assignments assess outcomes

### ISSUE THREAD

**Issue by mcm001** [jottocraft/dtps#19]
Can we get a way to view which assignments assess which outcomes? It doesn't seem too hard to do but I don't know javascript well enough to PR it.

**Comment by jottocraft** [comment]
You can see outcome assessments in the grades tab for each class or in each assignment.

Outcome assessments in the grades tab for each class. This includes each outcome, each assessment for each outcome, and the decaying average for each outcome. Individual outcome assessments were added over the weekend in https://github.com/jottocraft/dtps/commit/65e94690269d9d80a0e6f173e5bd866ab561493a.

![Outcome assessments in the grades tab](https://user-images.githubusercontent.com/11508240/65465325-cfe14200-de10-11e9-801f-9a0e402513ce.png)

Outcome assessments in each assignment
![Outcome assessments for each assignment](https://user-images.githubusercontent.com/11508240/65465395-0a4adf00-de11-11e9-9bd5-d1e9220d7350.png)

**Comment by mcm001** [comment]
I'm looking at my English class's grades tab and I'm not seeing the same thing. I can see that 4 assignments assess this outcome, but I can't see which 4 assess it. Am I looking in the wrong place?

<img width="1056" alt="Screen Shot 2019-09-23 at 3 27 33 PM" src="https://user-images.githubusercontent.com/29715865/65467676-e9858800-de16-11e9-8d2d-0cd04da08072.png">
<img width="1215" alt="Screen Shot 2019-09-23 at 3 27 40 PM" src="https://user-images.githubusercontent.com/29715865/65467675-e9858800-de16-11e9-8941-d2d937f3e64e.png">

**Comment by jottocraft** [comment]
Oh, I see what you mean. The number of assignments that asses each outcome counts all assignments while the list only displays graded assignments. I'll probably add all of the alignments under the outcome details page some time soon.

**Comment by mcm001** [comment]
It looks like the titles of the aligments which assess each outcome are already stored under each class's `outcomes[i].aligments[j].title`. But putting them on the outcome details page would be great.

**Comment by jottocraft** [comment]
All outcome alignments are now listed in the outcome details page. Also, you can now click on an outcome alignment in the grades tab or in the outcome details page to view the assignment's details. 
https://github.com/jottocraft/dtps/commit/c11edab9bce48232610b7507fd076b80d13d86e9

![image](https://user-images.githubusercontent.com/11508240/65558614-59b20d80-deec-11e9-86dd-e965ad921ade.png)
