### ISSUE TITLE
Parent access?

### ISSUE THREAD

**Issue by andyjohnston2** [jottocraft/dtps#21]
Hi there - my son showed me this great tool.  Thank you so much for creating it!  When he installed it on my Chrome browser, and I logged into Canvas, it doesn't show the grades.  It looks like it is loading perpetually, but never finishes.  Is it supposed to work for parents?  No problem if so - I was just curious, and thought it would be helpful for parents to also have access to this useful tool.

Thanks,
Andy

**Comment by jottocraft** [comment]
Thanks for the feedback! I've added parent account support in Power+ (https://github.com/jottocraft/dtps/commit/5cd9b690ad6a7681a99dbb52ddecc3ece26f9bdd). Most things should be working for parent accounts, but there might still be some bugs. Hopefully everything you need is working now.
