### ISSUE TITLE
Missing assignments

### ISSUE THREAD

**Issue by TroySchmidt** [jottocraft/dtps#28]
On the dashboard it would be great to have a list of missing assignments so you could address them quickly.  Also as a parent observer of 4 children with over 25 classes to monitor having a single place to see anything missing when checking would be awesome!

Great tool.

**Comment by jottocraft** [comment]
Thanks for the feedback. I'm currently working on a UI refresh for Power+, so I'll be sure to add a missing assignments feature and improved parent account support to it. It should be ready by around January or February next year.

**Comment by TroySchmidt** [comment]
Kind of in line with that it would be nice to click on the map and the upcoming panel to start from that day.  Or if the calendar showed missing assignments in a different coloring or highlighted somehow to bring attention to them.

**Comment by jottocraft** [comment]
I've added a way to click on the calendar to see assignments from that date and a way to see missing assignments in the latest version of Power+. To see missing assignments, type "type:assignment" in the search bar and select the missing filter. I plan on adding additional ways to filter assignments and improving the overall experience in the future.
