### ISSUE TITLE
Grades having a precision issue

### ISSUE THREAD

**Issue by TroySchmidt** [jottocraft/dtps#30]
The grades have a precision issue.  Would probably be a good idea to round them to two decimals and then format them to zero or two decimal places.
![image](https://user-images.githubusercontent.com/1536877/101542560-ec638e80-3970-11eb-930d-5582c1b0cff9.png)

**Comment by jottocraft** [comment]
Thanks for the feedback. I've added rounding (to 2 decimal places) for assignment scores and fixed some of the CSS issues shown in your screenshot.

**Comment by TroySchmidt** [comment]
On a side note, the hover to see the corresponding percent is pretty cool!
