### ISSUE TITLE
Custom themes?

### ISSUE THREAD

**Issue by nickhasoccured** [jottocraft/dtps#33]
The chrome web store page said there was support for custom themes, but I couldn't find any documentation on how to use them, could anyone point me in the right direction? Thanks!

**Comment by jottocraft** [comment]
Unfortunately, I ended up removing custom theme support from Power+ for the time being since it isn't fully working. I'll make sure to update the Chrome Web Store listing to reflect this. Custom theme support should be ready in about a month or so.

**Comment by jottocraft** [comment]
I've added custom background image support to Power+ in v3.1.2 (https://github.com/jottocraft/dtps/commit/b3a6fff8d10e6df1490d6c63f2a525097ca27e18). I might add additional custom theming options in the future, but this is all that I have planned for now.
