### ISSUE TITLE
Opt-out of Analytics

### ISSUE THREAD

**Issue by nickhasoccured** [jottocraft/dtps#34]
Google Analytics isn't exactly the best privacy-wise, could we maybe get an option out opt out of analytics? You could also use an alternative that's better privacy wise.

**Comment by jottocraft** [comment]
Hello,
The privacy settings in Google Analytics for Power+ are set to disallow ad personalization, signals from users' Google accounts, and data sharing with Google or other third parties for all Power+ users. If you wish to disable Google Analytics in Power+, I have added an analytics opt-out button in Settings -> About -> Advanced Options (https://github.com/jottocraft/dtps/commit/adf75ff111764f78f3e7c2ed26a8dc01c57585a5). I would also consider installing the [Google Analytics opt-out extension](https://chrome.google.com/webstore/detail/google-analytics-opt-out/fllaojicojecljbmefodhfapmkghcbnh?hl=en) if you are concerned about your privacy with Google Analytics across other websites as well.

**Comment by nickhasoccured** [comment]
Thanks!
