### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by nchristopher** [jottocraft/dtps#42]
This extension is great, and I love using it everyday for Canvas. It'd be great to have Firefox support alongside Chromium support, however. I'm not sure if this is a matter of just porting it, or would require a re-write.

If it's the latter, this issue can be closed; obviously that's too much of an ask.

**Comment by jottocraft** [comment]
Thanks for the feedback. I've published the Power+ extension to the Firefox Add-Ons catalog [here](https://addons.mozilla.org/en-US/firefox/addon/dtps). The Firefox version uses the same codebase as the Chromium extension, so it should stay up-to-date across both platforms.
