### ISSUE TITLE
assignment sorting

### ISSUE THREAD

**Issue by 3052** [jottocraft/dtps#6]
**What do you want to be added in Power+?**
sort assignments is useful to find stuff\
should be an option to sort on every page that has assignments listed (inc. dashboard)
also include exams in the list of stuff too and i forgot but add an option under filter to show exams thanks
concepts:
![image](https://user-images.githubusercontent.com/31232125/50046563-17ed6000-005a-11e9-9a9d-75f4932fb0b1.png)
![image](https://user-images.githubusercontent.com/31232125/50046618-d8734380-005a-11e9-9604-123b03eca709.png)

**Comment by jottocraft** [comment]
search finished and will ship in v1.4.0. should hit stable next week and is live right now in dev. sorting assignments might come later, but is really low on the priority list, so probably not even in v1.5.0.
