### ISSUE TITLE
calander broken on edge/firefox

### ISSUE THREAD

**Issue by 3052** [jottocraft/dtps#7]
**Describe the bug**
calendar assignments not showing on firefox
![image](https://user-images.githubusercontent.com/31232125/50046663-aca48d80-005b-11e9-8572-9054a7a4ac69.png)

**Repo steps**
open firefox/any firefox based browser
log into powerschool as normal
load script **javascript:(function(){javascript:jQuery.getScript('https://dtps.js.org/init.js');dtpsLoader=2;})();**

**Expected behavior:**
when u look at the calander it has the stuff
![image](https://user-images.githubusercontent.com/31232125/50046678-1ae95000-005c-11e9-88c8-07b13e829d75.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/31232125/50046682-263c7b80-005c-11e9-978b-826350c4e196.png)
(i even showed some assisnments that should have been loaded)
PLUS
edge looks like this
![image](https://user-images.githubusercontent.com/31232125/50046693-3e13ff80-005c-11e9-988d-ed1ccd3df7b5.png)

**Desktop (please complete the following information):**
 - OS with version: [e.g. Windows 10, macOS Mojave]
- windows 10
-firefox newest whatever it is

**Comment by jottocraft** [comment]
no plans to fully support firefox at the moment. edgeHTML will never be supported since they're switching edge to chromium soon anyways. might look into this later in the future.
