### ISSUE TITLE
show code for other browsers

### ISSUE THREAD

**Issue by 3052** [jottocraft/dtps#8]
**What do you want to be added in Power+?**
on the website thing add the firefox version of the script:

`javascript:(function(){javascript:jQuery.getScript('https://dtps.js.org/init.js');dtpsLoader=2;})();`

Edit (by jottocraft):
Fixed some syntax, here's what this should be
`javascript:(function(){jQuery.getScript('https://dtps.js.org/init.js');dtpsLoader=2;})();`

**Comment by jottocraft** [comment]
will add this to power+ website although firefox isn't fully supported
